services:
    api:
        build:
            context: .
            dockerfile: Dockerfile

        ports:
            - "8080:8080"

        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            # General
            - ASPNETCORE_URLS=${ASPNETCORE_URLS}
            - TZ=${TZ}
            # Database
            # - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION_STRING}
            # RabbitMQ
            # - RabbitMQ__Host=${RABBITMQ_HOST}
            # - RabbitMQ__User=${RABBITMQ_USER}
            # - RabbitMQ__Password=${RABBITMQ_PASSWORD}
            # - RabbitMQ__VirtualHost=${RABBITMQ_VHOST}
            # - RabbitMQ__Port=${RABBITMQ_PORT}
            # JWT
            - Jwt__SecretKey=${JWT_SECRET_KEY}
            - Jwt__Issuer=${JWT_ISSUER}
            - Jwt__Audience=${JWT_AUDIENCE}
            # SendGrid
            - EmailSettings__ApiKey=${SENDGRID_API_KEY}
            # ZaloPay
            - ZaloPay__AppId=${ZALOPAY_APP_ID}
            - ZaloPay__Key1=${ZALOPAY_KEY1}
            - ZaloPay__Key2=${ZALOPAY_KEY2}
            - ZaloPay__CreateOrderUrl=${ZALOPAY_CREATE_ORDER_URL}
            - ZaloPay__CallbackUrl=${ZALOPAY_CALLBACK_URL}
            - ZaloPay__BankCode=${ZALOPAY_BANK_CODE}

        volumes:
            - uploads_data:/app/uploads

        depends_on:
            - db
            - message_broker

    db:
        image: postgres:15
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123
            - POSTGRES_DB=database
            - TZ=Asia/Ho_Chi_Minh
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./database/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
            - ./database/02_users.sql:/docker-entrypoint-initdb.d/02_users.sql:ro
            - ./database/03_categories.sql:/docker-entrypoint-initdb.d/03_categories.sql:ro
            - ./database/04_products.sql:/docker-entrypoint-initdb.d/04_products.sql:ro
            - ./database/05_product_categories.sql:/docker-entrypoint-initdb.d/05_product_categories.sql:ro
            - ./database/06_product_skus.sql:/docker-entrypoint-initdb.d/06_product_skus.sql:ro
            - ./database/07_product_images.sql:/docker-entrypoint-initdb.d/07_product_images.sql:ro
            - ./database/08_inventory.sql:/docker-entrypoint-initdb.d/08_inventory.sql:ro

    message_broker:
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
            - "15672:15672"

volumes:
    postgres_data:
    uploads_data:
