services:
    api:
        build:
            context: .
            dockerfile: Dockerfile

        ports:
            - "8080:8080"

        environment:
            # General
            - ASPNETCORE_URLS=${ASPNETCORE_URLS}
            - TZ=${TZ}
            # Database
            - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION_STRING}
            # RabbitMQ
            - RabbitMQ__Host=${RABBITMQ_HOST}
            - RabbitMQ__User=${RABBITMQ_USER}
            - RabbitMQ__Password=${RABBITMQ_PASSWORD}
            - RabbitMQ__VirtualHost=${RABBITMQ_VHOST}
            - RabbitMQ__Port=${RABBITMQ_PORT}
            # JWT
            - Jwt__SecretKey=${JWT_SECRET_KEY}
            - Jwt__Issuer=${JWT_ISSUER}
            - Jwt__Audience=${JWT_AUDIENCE}
            # SendGrid
            - EmailSettings__ApiKey=${SENDGRID_API_KEY}
            # ZaloPay
            - ZaloPay__AppId=${ZALOPAY_APP_ID}
            - ZaloPay__Key1=${ZALOPAY_KEY1}
            - ZaloPay__Key2=${ZALOPAY_KEY2}
            - ZaloPay__CreateOrderUrl=${ZALOPAY_CREATE_ORDER_URL}
            - ZaloPay__CallbackUrl=${ZALOPAY_CALLBACK_URL}
            - ZaloPay__BankCode=${ZALOPAY_BANK_CODE}

        volumes:
            - uploads_data:/app/uploads

    # chatbot_api:
    #     build:
    #         context: ./ai-module/
    #         dockerfile: Dockerfile
    #     ports:
    #     - "8000:8000"
    #     environment:
    #     - DB_HOST=db
    #     - DB_NAME=database
    #     - DB_USER=postgres
    #     - DB_PASSWORD=${POSTGRES_PASSWORD} # Use variable
    #     - DB_PORT=5432
    #     - CHROMA_DB_PATH=/app/chroma_db
    #     - GOOGLE_API_KEY=${GOOGLE_API_KEY} # Use variable
    #     depends_on:
    #     - db
    #     volumes:
    #     - ./ai-module/app:/app/app
    #     - ./ai-module/data/vector/chroma_db_data1:/app/chroma_db

volumes:
    uploads_data:
