INSERT INTO product_skus (
        product_id,
        sku,
        color,
        size,
        price,
        is_default
    )
SELECT p.product_id,
    mapping.sku,
    mapping.color,
    mapping.size,
    mapping.price,
    mapping.is_default
FROM (
        VALUES (
                'striped-knit-polo-shirt',
                'RO114B6H-1',
                'White',
                'S',
                500000,
                TRUE
            ),
            (
                'striped-knit-polo-shirt',
                'RO114B6H-2',
                'White',
                'M',
                500000,
                FALSE
            ),
            (
                'striped-knit-polo-shirt',
                'RO114B6H-3',
                'White',
                'L',
                500000,
                FALSE
            ),
            (
                'studded-cotton-crew-tee',
                'H3747ZE5-1',
                'Black',
                'S',
                450000,
                TRUE
            ),
            (
                'studded-cotton-crew-tee',
                'H3747ZE5-2',
                'Black',
                'M',
                450000,
                FALSE
            ),
            (
                'studded-cotton-crew-tee',
                'H3747ZE5-3',
                'Black',
                'L',
                450000,
                FALSE
            ),
            (
                'baggy-tokyo-racing-graphic-jersey',
                'J3PS7IXM-1',
                'White',
                'S',
                430000,
                TRUE
            ),
            (
                'baggy-tokyo-racing-graphic-jersey',
                'J3PS7IXM-2',
                'White',
                'M',
                430000,
                FALSE
            ),
            (
                'baggy-tokyo-racing-graphic-jersey',
                'J3PS7IXM-3',
                'White',
                'L',
                430000,
                FALSE
            ),
            (
                'baggy-tokyo-racing-graphic-jersey',
                'J3PS7IXM-4',
                'Blue',
                'S',
                430000,
                FALSE
            ),
            (
                'baggy-tokyo-racing-graphic-jersey',
                'J3PS7IXM-5',
                'Blue',
                'M',
                430000,
                FALSE
            ),
            (
                'baggy-tokyo-racing-graphic-jersey',
                'J3PS7IXM-6',
                'Blue',
                'L',
                430000,
                FALSE
            ),
            (
                'boxy-heavyweight-graphic-cutoff-tank',
                'FN3LIUQO-1',
                'Beige',
                'S',
                350000,
                TRUE
            ),
            (
                'boxy-heavyweight-graphic-cutoff-tank',
                'FN3LIUQO-2',
                'Beige',
                'M',
                350000,
                FALSE
            ),
            (
                'boxy-heavyweight-graphic-cutoff-tank',
                'FN3LIUQO-3',
                'Beige',
                'L',
                350000,
                FALSE
            ),
            (
                'evolution-straight-leg-sweatpants',
                'X9QN9M9X-1',
                'Black',
                'S',
                550000,
                TRUE
            ),
            (
                'evolution-straight-leg-sweatpants',
                'X9QN9M9X-2',
                'Black',
                'M',
                550000,
                FALSE
            ),
            (
                'evolution-straight-leg-sweatpants',
                'X9QN9M9X-3',
                'Black',
                'L',
                550000,
                FALSE
            ),
            (
                'slim-taper-chino-pants',
                'QV0VDLRA-1',
                'Black',
                'M',
                500000,
                TRUE
            ),
            (
                'baggy-utility-pants',
                '98Q0ZF2A-1',
                'Green',
                'M',
                600000,
                TRUE
            ),
            (
                'baggy-jeans-bag-secured',
                'H6MJZ41U-1',
                'Blue',
                'M',
                570000,
                TRUE
            ),
            (
                'cotton-workwear-jacket',
                '8NGTJMG0-1',
                'Beige',
                'S',
                1200000,
                TRUE
            ),
            (
                'cotton-workwear-jacket',
                '8NGTJMG0-2',
                'Beige',
                'M',
                1200000,
                FALSE
            ),
            (
                'cotton-workwear-jacket',
                '8NGTJMG0-3',
                'Beige',
                'L',
                1200000,
                FALSE
            ),
            (
                'cotton-workwear-jacket',
                '8NGTJMG0-4',
                'Black',
                'S',
                1200000,
                FALSE
            ),
            (
                'cotton-workwear-jacket',
                '8NGTJMG0-5',
                'Black',
                'M',
                1200000,
                FALSE
            ),
            (
                'cotton-workwear-jacket',
                '8NGTJMG0-6',
                'Black',
                'L',
                1200000,
                FALSE
            ),
            (
                'loose-fit-scuba-baseball-jacket',
                'MKECNL4I-1',
                'White',
                'M',
                1150000,
                TRUE
            ),
            (
                'vaporfly-4',
                'N4E8JUPO-1',
                'White',
                '38',
                3990000,
                TRUE
            ),
            (
                'vaporfly-4',
                'N4E8JUPO-2',
                'White',
                '39',
                3990000,
                FALSE
            ),
            (
                'vaporfly-4',
                'N4E8JUPO-3',
                'White',
                '40',
                3990000,
                FALSE
            ),
            (
                'vaporfly-4',
                'N4E8JUPO-4',
                'White',
                '41',
                3990000,
                FALSE
            ),
            (
                'vaporfly-4',
                'N4E8JUPO-5',
                'White',
                '42',
                3990000,
                FALSE
            ),
            (
                'vaporfly-4',
                'N4E8JUPO-6',
                'White',
                '43',
                3990000,
                FALSE
            ),
            (
                'vaporfly-4',
                'N4E8JUPO-7',
                'White',
                '44',
                3990000,
                FALSE
            ),
            (
                'giannis-freak-7-ep',
                'GPBVGXLZ-1',
                'Yellow',
                '42',
                3560000,
                TRUE
            ),
            (
                'dri-fit-club-cap',
                'Q3BWOG1P-1',
                'Black',
                'S',
                300000,
                TRUE
            ),
            (
                'jersey-knit-puff-sleeve-top',
                'K619WC9A-1',
                'White',
                'XS',
                670000,
                TRUE
            ),
            (
                'jersey-knit-puff-sleeve-top',
                'K619WC9A-2',
                'White',
                'S',
                670000,
                FALSE
            ),
            (
                'jersey-knit-puff-sleeve-top',
                'K619WC9A-3',
                'White',
                'M',
                670000,
                FALSE
            ),
            (
                'jersey-knit-puff-sleeve-top',
                'K619WC9A-4',
                'Black',
                'XS',
                670000,
                FALSE
            ),
            (
                'jersey-knit-puff-sleeve-top',
                'K619WC9A-5',
                'Black',
                'S',
                670000,
                FALSE
            ),
            (
                'jersey-knit-puff-sleeve-top',
                'K619WC9A-6',
                'Black',
                'M',
                670000,
                FALSE
            ),
            (
                'embroidered-bow-cropped-tee',
                '2RLGTUVA-1',
                'White',
                'S',
                450000,
                TRUE
            ),
            (
                'open-knit-crochet-sweater',
                'I4H839K2-1',
                'Green',
                'S',
                530000,
                TRUE
            ),
            (
                'tube-mesh-midi-dress',
                'B9VYVZRA-1',
                'Black',
                'S',
                900000,
                TRUE
            ),
            (
                'eyelet-bustier-flounce-mini-dress',
                'FTEXAFYQ-1',
                'White',
                'S',
                780000,
                TRUE
            ),
            (
                'adizero-adios-pro-4',
                '44L9DNR7-1',
                'Green',
                '38',
                3800000,
                TRUE
            ),
            (
                'superstar-ii',
                '3PIO2A7J-1',
                'Gray',
                '38',
                2500000,
                TRUE
            ),
            (
                'adicolor-classic-trefoil-baseball-cap',
                'JXYCZAYU-1',
                'Blue',
                'S',
                300000,
                TRUE
            ),
            (
                'noveau-signature-patch-varsity-jacket',
                'NSKWIUUS-1',
                'Beige',
                'S',
                1690000,
                TRUE
            ),
            (
                'noveau-signature-patch-varsity-jacket',
                'NSKWIUUS-2',
                'Beige',
                'M',
                1690000,
                FALSE
            ),
            (
                'noveau-signature-patch-varsity-jacket',
                'NSKWIUUS-3',
                'Beige',
                'L',
                1690000,
                FALSE
            ),
            (
                'pokemon-ut-graphic-t-shirt',
                'MS2H5MFU-1',
                'Black',
                'S',
                460000,
                TRUE
            ),
            (
                'pokemon-ut-graphic-t-shirt',
                'MS2H5MFU-2',
                'Black',
                'M',
                460000,
                FALSE
            ),
            (
                'pokemon-ut-graphic-t-shirt',
                'MS2H5MFU-3',
                'Black',
                'L',
                460000,
                FALSE
            ),
            (
                'pokemon-ut-graphic-t-shirt-1',
                'MS2H5MAK-1',
                'White',
                'S',
                460000,
                TRUE
            ),
            (
                'pokemon-ut-graphic-t-shirt-1',
                'MS2H5MAK-2',
                'White',
                'M',
                460000,
                FALSE
            ),
            (
                'pokemon-ut-graphic-t-shirt-1',
                'MS2H5MAK-3',
                'White',
                'L',
                460000,
                FALSE
            ),
            (
                'pokemon-ut-graphic-t-shirt-2',
                'MS2H5MRM-1',
                'Blue',
                'S',
                460000,
                TRUE
            ),
            (
                'pokemon-ut-graphic-t-shirt-2',
                'MS2H5MRM-2',
                'Blue',
                'M',
                460000,
                FALSE
            ),
            (
                'pokemon-ut-graphic-t-shirt-2',
                'MS2H5MRM-3',
                'Blue',
                'L',
                460000,
                FALSE
            )
    ) AS mapping(
        product_slug,
        sku,
        color,
        size,
        price,
        is_default
    )
    JOIN products p ON p.slug = mapping.product_slug;