INSERT INTO inventory (
    sku_id,
    quantity_available,
    reorder_point,
    reorder_quantity
)
SELECT
    s.sku_id,
    mapping.quantity_available,
    mapping.reorder_point,
    mapping.reorder_quantity
FROM (
    VALUES
        (
            'RO114B6H-1',
            8,
            3,
            10
        ),
        (
            'RO114B6H-2',
            8,
            3,
            10
        ),
        (
            'RO114B6H-3',
            8,
            3,
            10
        ),
        (
            'H3747ZE5-1',
            8,
            3,
            10
        ),
        (
            'H3747ZE5-2',
            8,
            3,
            10
        ),
        (
            'H3747ZE5-3',
            8,
            3,
            10
        ),
        (
            'J3PS7IXM-1',
            8,
            3,
            10
        ),
        (
            'J3PS7IXM-2',
            8,
            3,
            10
        ),
        (
            'J3PS7IXM-3',
            8,
            3,
            10
        ),
        (
            'J3PS7IXM-4',
            8,
            3,
            10
        ),
        (
            'J3PS7IXM-5',
            8,
            3,
            10
        ),
        (
            'J3PS7IXM-6',
            8,
            3,
            10
        ),
        (
            'FN3LIUQO-1',
            8,
            3,
            10
        ),
        (
            'FN3LIUQO-2',
            8,
            3,
            10
        ),
        (
            'FN3LIUQO-3',
            8,
            3,
            10
        ),
        (
            'X9QN9M9X-1',
            5,
            2,
            8
        ),
        (
            'X9QN9M9X-2',
            5,
            2,
            8
        ),
        (
            'X9QN9M9X-3',
            5,
            2,
            8
        ),
        (
            'QV0VDLRA-1',
            5,
            2,
            8
        ),
        (
            '98Q0ZF2A-1',
            5,
            2,
            8
        ),
        (
            'H6MJZ41U-1',
            5,
            2,
            8
        ),
        (
            '8NGTJMG0-1',
            5,
            2,
            8
        ),
        (
            '8NGTJMG0-2',
            5,
            2,
            8
        ),
        (
            '8NGTJMG0-3',
            5,
            2,
            8
        ),
        (
            '8NGTJMG0-4',
            5,
            2,
            8
        ),
        (
            '8NGTJMG0-5',
            5,
            2,
            8
        ),
        (
            '8NGTJMG0-6',
            5,
            2,
            8
        ),
        (
            'MKECNL4I-1',
            5,
            2,
            8
        ),
        (
            'N4E8JUPO-1',
            3,
            1,
            3
        ),
        (
            'N4E8JUPO-2',
            3,
            1,
            3
        ),
        (
            'N4E8JUPO-3',
            3,
            1,
            3
        ),
        (
            'N4E8JUPO-4',
            3,
            1,
            3
        ),
        (
            'N4E8JUPO-5',
            3,
            1,
            3
        ),
        (
            'N4E8JUPO-6',
            3,
            1,
            3
        ),
        (
            'N4E8JUPO-7',
            3,
            1,
            3
        ),
        (
            'GPBVGXLZ-1',
            3,
            1,
            3
        ),
        (
            'Q3BWOG1P-1',
            3,
            1,
            3
        ),
        (
            'K619WC9A-1',
            4,
            2,
            4
        ),
        (
            'K619WC9A-2',
            4,
            2,
            4
        ),
        (
            'K619WC9A-3',
            4,
            2,
            4
        ),
        (
            'K619WC9A-4',
            4,
            2,
            4
        ),
        (
            'K619WC9A-5',
            4,
            2,
            4
        ),
        (
            'K619WC9A-6',
            4,
            2,
            4
        ),
        (
            '2RLGTUVA-1',
            4,
            2,
            4
        ),
        (
            'I4H839K2-1',
            4,
            2,
            4
        ),
        (
            'B9VYVZRA-1',
            4,
            2,
            4
        ),
        (
            'FTEXAFYQ-1',
            4,
            2,
            4
        ),
        (
            '44L9DNR7-1',
            3,
            1,
            3
        ),
        (
            '3PIO2A7J-1',
            3,
            1,
            3
        ),
        (
            'JXYCZAYU-1',
            3,
            1,
            3
        )
) AS mapping(
    sku,
    quantity_available,
    reorder_point,
    reorder_quantity
)
JOIN product_skus s
    ON s.sku = mapping.sku;
